### ISSUE TITLE
code fences in markdown lose leading whitespace

### ISSUE THREAD

**Issue by TylerLeonhardt** [dotnet/interactive#542]
### Describe the bug

Consider the following markdown in a markdown cell:

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 2
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports:
            - containerPort: 80
    ```

The leading whitespace is gone:

![image](https://user-images.githubusercontent.com/2644648/84703608-64468400-af0d-11ea-8bcf-0004614f25bf.png)

### Please complete the following:

**Which version of .NET Interactive are you using?** There are a few ways to find this out:

* In a notebook, run the `#!about` magic command. 
* At the command line, run `dotnet interactive --version`.
* In VS Code, run "Report installed version for .NET Interactive` and copy the version number from the status popup.

( Looks like a vscode extension issue so should be .NET Interactive version agnostic )

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)
